export const wagmiAbi = [
  { type: "constructor", stateMutability: "nonpayable", inputs: [] },
  {
    type: "event",
    name: "CollateralDeposited",
    inputs: [
      {
        type: "uint256",
        name: "loanId",
        internalType: "uint256",
        indexed: true,
      },
      {
        type: "address",
        name: "borrower",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "amount",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CreditScoreDecreased",
    inputs: [
      {
        type: "address",
        name: "userAddress",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "newCreditScore",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CreditScoreIncreased",
    inputs: [
      {
        type: "address",
        name: "userAddress",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "newCreditScore",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LoanDefaulted",
    inputs: [
      {
        type: "uint256",
        name: "loanId",
        internalType: "uint256",
        indexed: true,
      },
      {
        type: "address",
        name: "borrower",
        internalType: "address",
        indexed: true,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LoanFunded",
    inputs: [
      {
        type: "uint256",
        name: "loanId",
        internalType: "uint256",
        indexed: true,
      },
      {
        type: "address",
        name: "lender",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "amount",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LoanRepaid",
    inputs: [
      {
        type: "uint256",
        name: "loanId",
        internalType: "uint256",
        indexed: true,
      },
      {
        type: "address",
        name: "borrower",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "amount",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LoanRequested",
    inputs: [
      {
        type: "uint256",
        name: "loanId",
        internalType: "uint256",
        indexed: true,
      },
      {
        type: "address",
        name: "borrower",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "amount",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "duration",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        type: "address",
        name: "previousOwner",
        internalType: "address",
        indexed: true,
      },
      {
        type: "address",
        name: "newOwner",
        internalType: "address",
        indexed: true,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProposalAccepted",
    inputs: [
      {
        type: "uint256",
        name: "loanId",
        internalType: "uint256",
        indexed: true,
      },
      {
        type: "address",
        name: "borrower",
        internalType: "address",
        indexed: true,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ProposalMade",
    inputs: [
      {
        type: "uint256",
        name: "loanId",
        internalType: "uint256",
        indexed: true,
      },
      {
        type: "address",
        name: "lender",
        internalType: "address",
        indexed: true,
      },
      {
        type: "uint256",
        name: "interestRate",
        internalType: "uint256",
        indexed: false,
      },
      {
        type: "uint256",
        name: "collateralAmount",
        internalType: "uint256",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "UserRegistered",
    inputs: [
      {
        type: "address",
        name: "userAddress",
        internalType: "address",
        indexed: true,
      },
      { type: "string", name: "email", internalType: "string", indexed: false },
      {
        type: "string",
        name: "phoneNumber",
        internalType: "string",
        indexed: false,
      },
    ],
    anonymous: false,
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "DEFAULT_DECREASE",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "FEE_PERCENTAGE",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "MAX_CREDIT_SCORE",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "REPAYMENT_INCREASE",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "acceptProposal",
    inputs: [{ type: "uint256", name: "_loanId", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "createLoanRequest",
    inputs: [
      { type: "uint256", name: "_amount", internalType: "uint256" },
      { type: "uint256", name: "_duration", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "depositCollateral",
    inputs: [{ type: "uint256", name: "_loanId", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "payable",
    outputs: [],
    name: "fundLoan",
    inputs: [{ type: "uint256", name: "_loanId", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "tuple",
        name: "",
        internalType: "struct P2PLoanMarketplace.LoanContract",
        components: [
          { type: "uint256", name: "loanId", internalType: "uint256" },
          { type: "address", name: "lender", internalType: "address" },
          { type: "uint256", name: "amount", internalType: "uint256" },
          { type: "uint256", name: "interestRate", internalType: "uint256" },
          { type: "uint256", name: "duration", internalType: "uint256" },
          { type: "uint256", name: "startDate", internalType: "uint256" },
          { type: "uint256", name: "endDate", internalType: "uint256" },
          { type: "bool", name: "isRepaid", internalType: "bool" },
        ],
      },
    ],
    name: "getLoanContract",
    inputs: [{ type: "uint256", name: "_loanId", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "tuple",
        name: "",
        internalType: "struct P2PLoanMarketplace.LoanRequest",
        components: [
          { type: "uint256", name: "id", internalType: "uint256" },
          { type: "address", name: "borrower", internalType: "address" },
          { type: "uint256", name: "amount", internalType: "uint256" },
          { type: "uint256", name: "duration", internalType: "uint256" },
          {
            type: "uint8",
            name: "status",
            internalType: "enum P2PLoanMarketplace.LoanStatus",
          },
        ],
      },
    ],
    name: "getLoanRequest",
    inputs: [{ type: "uint256", name: "_loanId", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      {
        type: "tuple",
        name: "",
        internalType: "struct P2PLoanMarketplace.Proposal",
        components: [
          { type: "uint256", name: "loanId", internalType: "uint256" },
          { type: "address", name: "lender", internalType: "address" },
          { type: "uint256", name: "interestRate", internalType: "uint256" },
          {
            type: "uint256",
            name: "collateralAmount",
            internalType: "uint256",
          },
          { type: "address", name: "collateral", internalType: "address" },
          { type: "bool", name: "isAccepted", internalType: "bool" },
        ],
      },
    ],
    name: "getProposal",
    inputs: [{ type: "uint256", name: "_loanId", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "uint256", name: "", internalType: "uint256" }],
    name: "getUserCreditScore",
    inputs: [{ type: "address", name: "userAddress", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "string", name: "", internalType: "string" },
      { type: "string", name: "", internalType: "string" },
      { type: "bool", name: "", internalType: "bool" },
    ],
    name: "getUserDetails",
    inputs: [{ type: "address", name: "userAddress", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "handleDefault",
    inputs: [{ type: "uint256", name: "_loanId", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "uint256", name: "loanId", internalType: "uint256" },
      { type: "address", name: "lender", internalType: "address" },
      { type: "uint256", name: "amount", internalType: "uint256" },
      { type: "uint256", name: "interestRate", internalType: "uint256" },
      { type: "uint256", name: "duration", internalType: "uint256" },
      { type: "uint256", name: "startDate", internalType: "uint256" },
      { type: "uint256", name: "endDate", internalType: "uint256" },
      { type: "bool", name: "isRepaid", internalType: "bool" },
    ],
    name: "loanContracts",
    inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "uint256", name: "id", internalType: "uint256" },
      { type: "address", name: "borrower", internalType: "address" },
      { type: "uint256", name: "amount", internalType: "uint256" },
      { type: "uint256", name: "duration", internalType: "uint256" },
      {
        type: "uint8",
        name: "status",
        internalType: "enum P2PLoanMarketplace.LoanStatus",
      },
    ],
    name: "loanRequests",
    inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "makeProposal",
    inputs: [
      { type: "uint256", name: "_loanId", internalType: "uint256" },
      { type: "uint256", name: "_interestRate", internalType: "uint256" },
      { type: "uint256", name: "_collateralAmount", internalType: "uint256" },
      { type: "address", name: "_collateral", internalType: "address" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [{ type: "address", name: "", internalType: "address" }],
    name: "owner",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "uint256", name: "loanId", internalType: "uint256" },
      { type: "address", name: "lender", internalType: "address" },
      { type: "uint256", name: "interestRate", internalType: "uint256" },
      { type: "uint256", name: "collateralAmount", internalType: "uint256" },
      { type: "address", name: "collateral", internalType: "address" },
      { type: "bool", name: "isAccepted", internalType: "bool" },
    ],
    name: "proposals",
    inputs: [{ type: "uint256", name: "", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "registerUser",
    inputs: [
      { type: "string", name: "_email", internalType: "string" },
      { type: "string", name: "_phoneNumber", internalType: "string" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "renounceOwnership",
    inputs: [],
  },
  {
    type: "function",
    stateMutability: "payable",
    outputs: [],
    name: "repayLoan",
    inputs: [{ type: "uint256", name: "_loanId", internalType: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "transferOwnership",
    inputs: [{ type: "address", name: "newOwner", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "updateLoanRequest",
    inputs: [
      { type: "uint256", name: "_loanId", internalType: "uint256" },
      { type: "uint256", name: "_amount", internalType: "uint256" },
      { type: "uint256", name: "_duration", internalType: "uint256" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    outputs: [
      { type: "string", name: "email", internalType: "string" },
      { type: "string", name: "phoneNumber", internalType: "string" },
      { type: "uint256", name: "creditScore", internalType: "uint256" },
      { type: "bool", name: "isVerified", internalType: "bool" },
    ],
    name: "users",
    inputs: [{ type: "address", name: "", internalType: "address" }],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    outputs: [],
    name: "withdrawFunds",
    inputs: [{ type: "uint256", name: "_amount", internalType: "uint256" }],
  },
  { type: "receive", stateMutability: "payable" },
];
